### ISSUE TITLE
7362 SL -out of range

### ISSUE THREAD

**Issue by blub4747** [freifunk-darmstadt/fritz-tools#32]
Hi team,
I am trying to run your fritzflash.py tool.
I get the following error msg.
`Starting automatic image-selection!
-> Establishing connection to device!
--> Try 1 of 10
Traceback (most recent call last):
  File "/home/user/Downloads/fritzflash.py", line 392, in <module>
    imagefile = autoload_image(ip)
  File "/home/user/Downloads/fritzflash.py", line 274, in autoload_image
    env = ftp.getenv()
  File "/home/user/Downloads/fritzflash.py", line 49, in getenv
    fritzenv[l[0]] = l[1]
IndexError: list index out of range
`
What could be the the reason for this error msg ?
Thx, blub4747

**Comment by fsffunk** [comment]
Do you still have the issue? You could try out the latest version of this tool from here: https://github.com/maurerle/fritz-tools
